{{- if .Values.ui.ingress.enabled }}
{{- $serviceName := printf "%s-%s" (include "consul.fullname" .) "ui" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "consul.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.ui.ingress.annotations }}
  annotations:
    {{ tpl (toYaml .Values.ui.ingress.annotations) . | nindent 4 | trim }}
  {{- end}}
spec:
  rules:
  {{- range .Values.ui.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              {{- if .Values.global.tls.enabled }}
              servicePort: 443
              {{- else }}
              servicePort: 80
              {{- end }}
  {{- end -}}
  {{- if .Values.ui.ingress.tls }}
  tls:
    {{ tpl (toYaml .Values.ui.ingress.tls) . | nindent 4 | trim }}
  {{- end }}
{{- end }}
